name: Demo MMDT
on:
  push:
    branches:
      -main
    workflow_dispatch:

jobs:
  demo-mmdt:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run:echo "Hello World!"

steps:
  - name: Checkout repo content
        